$:
  vscode:
    - docker:
        image: mcr.microsoft.com/devcontainers/universal
        #image: mcr.microsoft.com/devcontainers/go:1.24
      services:
        - vscode
        - docker
      env:
        # 声明首次打开终端时自动执行的命令，支持多行文本
        CNB_WELCOME_CMD: |
          go version
          node -v
          python --version

feat*:
  push:
    - stages:
        - name: sync to github
          imports: https://cnb.cool/spencezhang/my-keys/-/blob/main/env.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/logzh/cnb-guide.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}