$:
  vscode:
    - docker:
        image: mcr.microsoft.com/devcontainers/universal
        #image: mcr.microsoft.com/devcontainers/go:1.24
      services:
        - vscode
        - docker
      env:
        CNB_WELCOME_EXECUTE_COMMAND: go version
      stages:
        - name: ls
          script: ls -al
        - name: go version
          script: go version
        - name: node v
          script: node -v
        - name: python v
          script: python --version

feat*:
  push:
    - stages:
        - name: sync to github
          imports: https://cnb.cool/spencezhang/my-keys/-/blob/main/env.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/logzh/cnb-guide.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}