$:
  push:
    - stages:
        - name: sync to github
          imports: https://cnb.cool/spencezhang/my-keys/-/blob/main/env.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/logzh/cnb-guide.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}